In [2]:
import pathlib
import sys
import os

# Hacky way to get to root package
if "notebooks" in os.getcwd():
    os.chdir("..")

In [3]:
%load_ext autoreload
%autoreload 2
    
import sys
from data_container import load_scouted_data
import pandas as pd
import plotly.express as px
pd.set_option('display.max_columns', None)

In [4]:
scouted_data = load_scouted_data()
scouted_data

,Scouter Initials,Match Number,Team and Robot,No Show,autoCarrotO,autoCarrotCakeO,autoCarrotL1,autoCarrotL2,autoCarrotL3,autoCarrotCakeL1,autoCarrotCakeL2,autoCarrotCakeL3,telCarrotO,telCarrotCakeO,telCarrotL1,telCarrotL2,telCarrotL3,telCarrotCakeL1,telCarrotCakeL2,telCarrotCakeL3,Auto Cross Kitchen Line,Auto Robot Stuck or Astop in Auto?,Harvest Haul Carrots,Harvest Haul Carrot Cakes,XXXXXX
0,abc,1,340,True,0,0,1,4,0,1,1,0,28,14,28,27,22,12,6,3,False,False,2,1,NaN
1,abc,1,3504,False,0,0,1,0,2,1,0,1,22,6,19,4,23,16,20,15,False,False,0,0,NaN
2,abc,1,3015,False,4,2,1,2,0,0,1,0,10,19,23,12,30,12,16,12,False,False,1,1,NaN
3,abc,1,2641,False,2,0,1,3,4,2,1,2,4,10,3,18,26,15,10,7,False,False,0,0,NaN
4,abc,1,3990,False,3,1,3,1,1,0,2,2,2,4,13,1,29,0,19,7,False,False,3,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,abc,32,10582,False,1,0,5,3,1,1,2,1,5,2,20,14,14,4,6,19,False,False,1,0,NaN
164,abc,32,1708,False,3,1,0,3,1,0,1,0,14,14,15,6,18,9,5,0,False,False,0,1,NaN
165,abc,32,11456,False,0,0,2,2,3,0,1,2,12,7,1,9,3,11,13,0,False,False,2,1,NaN
166,abc,32,8705,False,4,2,4,2,4,1,2,2,12,2,9,2,25,15,11,3,False,True,1,1,NaN
167,abc,32,10515,False,5,0,1,4,5,1,1,0,14,1,29,28,21,12,12,18,False,False,0,0,NaN

In [5]:
team_averages = scouted_data.groupby("Team and Robot").mean(numeric_only=True)
team_averages

,Match Number,No Show,autoCarrotO,autoCarrotCakeO,autoCarrotL1,autoCarrotL2,autoCarrotL3,autoCarrotCakeL1,autoCarrotCakeL2,autoCarrotCakeL3,telCarrotO,telCarrotCakeO,telCarrotL1,telCarrotL2,telCarrotL3,telCarrotCakeL1,telCarrotCakeL2,telCarrotCakeL3,Auto Cross Kitchen Line,Auto Robot Stuck or Astop in Auto?,Harvest Haul Carrots,Harvest Haul Carrot Cakes,XXXXXX
Team and Robot,,,,,,,,,,,,,,,,,,,,,,,
63,14.250000,0.000000,3.000000,0.750000,4.500000,2.000000,2.250000,1.250000,1.000000,1.000000,12.250000,8.500000,9.500000,13.000000,10.000000,8.500000,12.250000,12.750000,0.000000,0.500000,2.000000,0.500000,NaN
117,17.500000,0.000000,2.500000,0.500000,3.250000,1.500000,3.750000,0.500000,0.500000,1.750000,16.500000,9.750000,14.500000,18.750000,8.250000,8.000000,8.750000,11.500000,0.250000,0.250000,1.000000,0.500000,NaN
340,12.600000,0.400000,2.000000,0.800000,2.800000,2.800000,1.400000,1.200000,1.400000,0.600000,18.200000,6.200000,15.400000,18.800000,20.800000,10.800000,5.800000,6.800000,0.000000,0.000000,1.400000,0.600000,NaN
451,23.666667,0.000000,2.666667,1.000000,1.333333,4.666667,3.000000,1.333333,1.000000,1.666667,15.333333,17.000000,20.000000,21.666667,19.333333,7.333333,7.666667,15.666667,0.000000,0.000000,1.000000,0.333333,NaN
709,15.000000,0.000000,2.250000,1.000000,2.000000,1.500000,2.250000,1.250000,1.000000,1.000000,17.750000,7.000000,22.500000,20.500000,19.750000,10.000000,5.500000,9.750000,0.000000,0.000000,1.500000,0.750000,NaN
1317,19.666667,0.000000,2.333333,1.000000,1.666667,3.666667,3.666667,1.666667,0.333333,1.000000,9.333333,4.000000,17.666667,23.333333,18.000000,11.666667,1.666667,11.000000,0.000000,0.000000,2.666667,0.666667,NaN
1511,23.333333,0.000000,1.666667,1.333333,2.666667,3.666667,2.333333,1.666667,1.666667,1.666667,19.666667,14.666667,21.000000,17.333333,9.333333,15.000000,7.000000,7.000000,0.333333,0.000000,1.666667,0.666667,NaN
1601,19.333333,0.000000,2.000000,1.333333,2.666667,2.666667,2.333333,1.666667,1.000000,1.000000,14.666667,12.333333,10.333333,12.666667,16.666667,10.000000,8.666667,2.333333,0.000000,0.000000,2.000000,0.333333,NaN
1708,22.666667,0.000000,4.000000,1.000000,1.666667,2.000000,2.666667,1.000000,1.000000,1.333333,13.666667,11.333333,13.666667,11.000000,14.333333,9.333333,2.666667,11.333333,0.000000,0.000000,1.333333,0.666667,NaN
1816,15.500000,0.000000,3.500000,0.250000,3.750000,0.750000,2.500000,0.500000,1.000000,1.000000,23.750000,12.250000,11.000000,13.750000,19.250000,11.750000,13.000000,13.500000,0.000000,0.000000,1.250000,0.000000,NaN
2010,17.000000,0.000000,4.500000,2.000000,0.000000,3.500000,0.500000,1.000000,1.000000,0.500000,2.000000,10.000000,15.000000,18.000000,2.500000,12.000000,8.000000,8.500000,0.000000,0.000000,0.000000,0.500000,NaN
2095,11.333333,0.000000,4.000000,1.666667,2.333333,4.000000,3.333333,0.333333,0.666667,0.666667,13.666667,12.333333,18.333333,17.000000,9.000000,9.333333,12.666667,10.000000,0.000000,0.333333,0.000000,0.333333,NaN
2234,24.333333,0.000000,2.333333,0.666667,3.666667,0.333333,2.000000,1.666667,1.333333,0.000000,13.000000,12.333333,23.333333,9.666667,19.666667,6.000000,17.000000,14.000000,0.000000,0.000000,2.000000,0.333333,NaN
2614,19.666667,0.333333,2.666667,1.000000,2.333333,3.666667,1.333333,1.666667,0.666667,1.000000,14.333333,14.666667,11.333333,18.333333,15.333333,12.666667,7.000000,9.333333,0.000000,0.333333,2.666667,0.666667,NaN
2641,13.600000,0.200000,2.000000,1.000000,3.600000,3.400000,3.600000,1.600000,0.600000,1.600000,7.400000,11.400000,11.000000,9.400000,15.800000,13.000000,11.600000,3.800000,0.000000,0.000000,1.800000,0.200000,NaN
2656,22.666667,0.000000,3.000000,0.666667,0.333333,2.000000,2.000000,1.666667,1.000000,1.333333,16.000000,4.000000,13.000000,26.333333,26.000000,5.666667,9.333333,14.666667,0.000000,0.000000,2.000000,0.333333,NaN
3015,13.000000,0.200000,2.800000,0.600000,2.000000,2.400000,0.800000,0.000000,0.600000,1.200000,9.400000,10.200000,17.400000,15.200000,19.000000,13.600000,15.400000,14.600000,0.000000,0.000000,1.800000,0.800000,NaN
3173,21.666667,0.000000,0.666667,0.000000,2.333333,2.333333,3.000000,0.666667,1.000000,0.666667,17.000000,5.333333,16.666667,24.000000,1.666667,9.666667,5.666667,5.333333,0.000000,0.333333,1.000000,0.333333,NaN
3260,15.000000,0.000000,1.500000,1.000000,2.000000,4.000000,2.500000,0.750000,1.000000,0.250000,10.750000,9.750000,6.750000,18.000000,18.250000,8.250000,7.000000,7.500000,0.250000,0.000000,1.750000,0.250000,NaN
3324,15.666667,0.000000,1.666667,1.666667,3.333333,1.333333,4.666667,0.666667,0.333333,0.000000,14.000000,7.000000,17.000000,25.000000,7.333333,10.666667,15.666667,12.333333,0.000000,0.000000,2.000000,0.666667,NaN
3484,16.250000,0.500000,3.250000,1.250000,2.000000,2.750000,3.250000,0.500000,0.750000,0.750000,13.750000,15.500000,11.000000,18.750000,19.750000,8.500000,5.500000,10.250000,0.250000,0.250000,0.750000,0.500000,NaN
3504,11.000000,0.000000,1.666667,1.166667,3.000000,3.166667,2.333333,0.666667,0.333333,1.833333,21.666667,10.166667,16.833333,13.166667,15.000000,15.333333,10.000000,10.666667,0.166667,0.000000,0.833333,0.500000,NaN
3990,13.600000,0.200000,1.600000,0.600000,2.800000,0.600000,1.800000,1.000000,1.400000,0.800000,21.000000,9.200000,19.200000,12.200000,18.000000,7.600000,12.600000,7.800000,0.000000,0.000000,2.200000,0.800000,NaN
4027,20.333333,0.000000,2.333333,1.666667,3.666667,3.333333,4.333333,2.000000,1.000000,0.333333,22.333333,11.000000,14.666667,7.333333,4.000000,10.666667,13.666667,2.333333,0.000000,0.000000,1.333333,0.333333,NaN
4028,9.500000,0.000000,3.250000,1.750000,1.500000,3.000000,2.250000,1.500000,0.750000,0.750000,24.000000,8.500000,13.000000,20.500000,14.750000,13.000000,7.500000,9.000000,0.000000,0.250000,1.750000,0.500000,NaN
4050,22.333333,0.000000,3.333333,2.000000,1.666667,3.666667,2.333333,1.000000,1.000000,1.000000,22.333333,8.666667,11.333333,15.333333,17.000000,12.000000,10.333333,8.333333,0.000000,0.000000,0.666667,0.666667,NaN
4150,14.000000,0.000000,3.000000,1.000000,1.333333,1.000000,3.666667,0.333333,1.666667,1.333333,13.666667,8.000000,5.666667,5.666667,14.333333,13.000000,9.333333,12.333333,0.000000,0.000000,1.666667,0.333333,NaN
4269,16.750000,0.000000,3.000000,0.500000,3.750000,4.250000,1.000000,0.750000,1.750000,1.500000,15.500000,11.250000,6.000000,15.500000,16.250000,6.750000,6.750000,4.500000,0.000000,0.250000,2.500000,0.250000,NaN
4467,14.000000,0.000000,2.666667,1.333333,2.333333,1.000000,2.666667,1.333333,1.666667,0.333333,13.666667,12.666667,9.333333,18.333333,11.000000,11.333333,7.000000,10.000000,0.000000,0.000000,1.666667,0.666667,NaN
4991,20.333333,0.000000,2.666667,0.666667,3.333333,4.000000,3.333333,0.333333,0.666667,1.333333,12.000000,10.333333,13.000000,10.333333,16.666667,11.000000,10.333333,4.666667,0.000000,0.000000,1.333333,0.666667,NaN
5667,19.000000,0.000000,3.000000,1.000000,1.000000,1.666667,1.666667,0.666667,1.666667,0.666667,19.000000,10.333333,8.666667,10.000000,17.666667,9.666667,5.666667,6.000000,0.000000,0.000000,2.333333,0.000000,NaN
5740,19.666667,0.000000,1.666667,1.000000,1.333333,3.000000,2.333333,0.666667,1.333333,1.333333,14.333333,9.666667,18.000000,15.000000,12.000000,4.333333,14.333333,9.666667,0.000000,0.333333,2.000000,0.333333,NaN
6032,11.000000,0.000000,2.000000,1.333333,3.666667,4.000000,2.666667,0.666667,2.000000,1.333333,5.000000,17.666667,12.666667,13.000000,17.333333,1.000000,8.000000,4.000000,0.000000,0.000000,2.000000,0.666667,NaN
7274,18.666667,0.000000,4.000000,1.333333,2.000000,2.666667,2.333333,2.000000,1.000000,1.333333,10.333333,5.666667,18.000000,21.000000,22.666667,12.666667,6.333333,4.000000,0.000000,0.000000,0.333333,0.333333,NaN
7515,18.750000,0.250000,2.250000,1.500000,1.750000,2.500000,2.250000,1.500000,1.000000,1.250000,23.250000,10.250000,14.250000,12.750000,14.250000,3.000000,7.750000,10.000000,0.000000,0.000000,1.250000,0.750000,NaN
8705,16.500000,0.000000,3.500000,1.500000,3.000000,2.250000,3.750000,1.250000,1.000000,1.250000,19.000000,4.750000,12.000000,13.500000,10.000000,6.250000,7.250000,11.500000,0.000000,0.250000,1.250000,0.750000,NaN
9022,20.000000,0.000000,3.333333,0.666667,3.333333,2.000000,3.333333,1.333333,1.666667,0.666667,7.666667,10.000000,10.333333,17.666667,10.333333,11.666667,9.333333,13.666667,0.000000,0.000000,1.666667,0.333333,NaN
9406,15.333333,0.000000,1.000000,0.333333,1.666667,2.666667,3.333333,0.333333,1.666667,1.000000,17.000000,11.000000,6.333333,7.333333,12.000000,12.333333,12.666667,11.333333,0.000000,0.000000,2.666667,0.666667,NaN
9415,15.250000,0.000000,1.500000,0.750000,3.500000,2.250000,1.750000,0.750000,1.250000,1.250000,7.500000,8.250000,13.500000,17.250000,12.750000,8.000000,11.500000,10.500000,0.250000,0.000000,1.250000,0.250000,NaN
9475,23.000000,0.000000,4.000000,0.000000,3.500000,1.000000,2.500000,0.500000,0.500000,1.500000,19.000000,2.000000,9.000000,20.500000,5.000000,6.000000,17.500000,10.500000,0.000000,0.000000,3.000000,0.500000,NaN
9642,19.000000,0.000000,4.000000,1.000000,2.500000,0.500000,2.000000,0.500000,0.000000,2.000000,10.500000,9.000000,7.500000,27.000000,8.500000,9.000000,6.000000,12.500000,0.000000,0.000000,1.000000,1.000000,NaN
9653,19.000000,0.000000,3.000000,0.666667,2.666667,3.333333,2.333333,1.000000,1.000000,0.666667,19.333333,13.666667,26.000000,15.000000,8.333333,7.000000,9.666667,7.333333,0.000000,0.000000,1.666667,0.333333,NaN
10300,21.666667,0.000000,1.666667,0.333333,2.666667,1.000000,1.333333,0.666667,1.666667,1.333333,24.333333,9.333333,12.666667,14.000000,18.666667,12.333333,10.000000,16.666667,0.000000,0.000000,0.666667,0.000000,NaN
10512,22.333333,0.333333,2.333333,0.666667,2.666667,1.333333,2.666667,1.666667,1.000000,1.000000,9.000000,12.666667,23.666667,14.000000,17.000000,8.333333,9.000000,12.666667,0.000000,0.000000,0.333333,0.000000,NaN
10513,22.333333,0.000000,3.000000,0.666667,3.333333,2.000000,1.333333,1.666667,0.333333,1.000000,3.666667,13.333333,12.666667,10.333333,8.000000,7.000000,4.666667,14.666667,0.000000,0.000000,2.000000,0.666667,NaN
10515,21.666667,0.000000,2.666667,0.000000,1.000000,2.333333,2.000000,1.333333,0.333333,1.000000,13.666667,5.666667,22.333333,15.666667,14.000000,10.666667,14.000000,12.333333,0.000000,0.000000,2.000000,0.333333,NaN
10516,18.000000,0.000000,2.500000,1.500000,2.500000,3.000000,3.000000,0.000000,1.500000,1.500000,6.000000,13.000000,22.000000,19.500000,13.000000,11.000000,11.500000,3.500000,0.000000,0.000000,2.000000,0.500000,NaN
10517,22.333333,0.000000,0.666667,1.333333,2.000000,4.000000,2.000000,0.666667,0.666667,1.000000,12.666667,16.666667,12.333333,17.000000,10.000000,14.000000,8.333333,7.333333,0.000000,0.000000,2.666667,0.666667,NaN
10582,23.666667,0.333333,1.333333,0.333333,4.000000,3.333333,1.000000,1.666667,1.666667,1.000000,10.666667,9.000000,14.333333,15.333333,12.000000,7.000000,2.666667,17.666667,0.000000,0.000000,1.000000,0.333333,NaN
11456,24.000000,0.000000,0.666667,0.333333,3.000000,1.666667,1.666667,0.666667,0.666667,1.333333,19.000000,10.000000,19.666667,15.333333,8.333333,13.000000,6.333333,7.666667,0.000000,0.000000,1.666667,0.333333,NaN

In [6]:
kitchescross_average = df.groupby("Team and Robot")

#fig = px.scatter(team_averages, x="Tele Pantry Carrot Scoring", y="Auto Pantry Carrot Scoring", text=team_averages.index)

#fig.update_traces(textposition="middle left")

fig

ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['Match Number', 'No Show', 'autoCarrotO', 'autoCarrotCakeO', 'autoCarrotL1', 'autoCarrotL2', 'autoCarrotL3', 'autoCarrotCakeL1', 'autoCarrotCakeL2', 'autoCarrotCakeL3', 'telCarrotO', 'telCarrotCakeO', 'telCarrotL1', 'telCarrotL2', 'telCarrotL3', 'telCarrotCakeL1', 'telCarrotCakeL2', 'telCarrotCakeL3', 'Auto Cross Kitchen Line', 'Auto Robot Stuck or Astop in Auto?', 'Harvest Haul Carrots', 'Harvest Haul Carrot Cakes', 'XXXXXX'] but received: Tele Pantry Carrot Scoring